// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCioZzVrGSSLlfd7s4Rq9kdxvAYvnAlDDo',
    appId: '1:10808709308:web:4a5d5b336cbf61c91900b9',
    messagingSenderId: '10808709308',
    projectId: 'bbsbookingsystem',
    authDomain: 'bbsbookingsystem.firebaseapp.com',
    storageBucket: 'bbsbookingsystem.appspot.com',
    measurementId: 'G-1MF6C8NFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDuDyWcAD4dfJrppJJ_q8g5fhU03hOswU',
    appId: '1:10808709308:android:2f7b7fda69575ff71900b9',
    messagingSenderId: '10808709308',
    projectId: 'bbsbookingsystem',
    storageBucket: 'bbsbookingsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MNptCeKxJnh37R70xzN57M1KQCndZJY',
    appId: '1:10808709308:ios:bdde168a4e218cb81900b9',
    messagingSenderId: '10808709308',
    projectId: 'bbsbookingsystem',
    storageBucket: 'bbsbookingsystem.appspot.com',
    iosBundleId: 'com.example.bbsBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MNptCeKxJnh37R70xzN57M1KQCndZJY',
    appId: '1:10808709308:ios:bdde168a4e218cb81900b9',
    messagingSenderId: '10808709308',
    projectId: 'bbsbookingsystem',
    storageBucket: 'bbsbookingsystem.appspot.com',
    iosBundleId: 'com.example.bbsBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCioZzVrGSSLlfd7s4Rq9kdxvAYvnAlDDo',
    appId: '1:10808709308:web:9c73cbe8fe10cb621900b9',
    messagingSenderId: '10808709308',
    projectId: 'bbsbookingsystem',
    authDomain: 'bbsbookingsystem.firebaseapp.com',
    storageBucket: 'bbsbookingsystem.appspot.com',
    measurementId: 'G-DJEZZBT8NL',
  );
}
